# Generated by Django 5.0.6 on 2024-06-18 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.user",),
        ),
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.user",
                    ),
                ),
                ("experience", models.IntegerField()),
                (
                    "rate",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("skills", models.TextField()),
                (
                    "cv",
                    models.ImageField(
                        blank=True, null=True, upload_to="programmer_cv/"
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.user",),
        ),
        migrations.CreateModel(
            name="WebDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Networking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloudServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackEndDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminCustomerSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.programmer"
                    ),
                ),
            ],
        ),
    ]
