# Generated by Django 5.0.6 on 2024-06-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmer",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="programmer",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Frontend", "frontend"),
                    ("Backend", "backend"),
                    ("Core/Deep Learning", "core/deep learning"),
                    ("Cloud Practitioner", "cloud practitioner"),
                    ("Administrator", "administrator"),
                    ("Fullstack", "fullstack"),
                ],
                default="Fullstack",
                max_length=50,
            ),
        ),
    ]
